name: whw
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - affine=2.3.0=py_0
  - appdirs=1.4.3=py_1
  - attrs=20.1.0=pyh9f0ad1d_0
  - backcall=0.2.0=py_0
  - boost-cpp=1.72.0=h8e57a91_0
  - branca=0.4.1=py_0
  - brotlipy=0.7.0=py38h1e0a361_1000
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=hcf35c78_1003
  - cartopy=0.18.0=py38h172510d_0
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.1=py38h5bae8af_0
  - cfitsio=3.470=hce51eda_6
  - cftime=1.2.1=py38h8790de6_0
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - contextily=1.0.0=py_0
  - cryptography=3.1=py38h766eaa4_0
  - curl=7.71.1=he644dc0_5
  - cycler=0.10.0=py_2
  - dataclasses=0.7=py38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - expat=2.2.9=he1b5a44_2
  - fiona=1.8.13=py38h033e0f6_1
  - folium=0.11.0=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - freexl=1.0.5=h516909a_1002
  - gdal=3.0.4=py38h172510d_10
  - geographiclib=1.50=py_0
  - geopandas=0.8.1=py_0
  - geopy=2.0.0=pyh9f0ad1d_0
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=h05acad5_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.65.0=h6f030ca_0
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h3c11f04_101
  - hydrodata=0.7.3b0=py_0
  - icu=64.2=he1b5a44_1
  - idna=2.10=pyh9f0ad1d_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.15.2=py38_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - json-c=0.13.1=hbfbb72e_1002
  - jupyter_client=6.1.6=py_0
  - jupyter_core=4.6.3=py38_0
  - kealib=1.4.13=h33137a7_1
  - kiwisolver=1.2.0=py38hbf85e49_0
  - krb5=1.17.1=hfafb76e_3
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.71.1=hcdd3856_5
  - libdap4=3.20.6=h1d1bd15_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgdal=3.0.4=he6a97d6_10
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=hb574062_1011
  - liblapack=3.8.0=17_openblas
  - libnetcdf=4.7.4=nompi_h84807e1_105
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libpq=12.3=h5513abc_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=he1b5a44_3
  - libspatialite=4.3.0a=h2482549_1038
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - libxslt=1.1.33=h31b3aaa_0
  - lxml=4.5.2=py38hbb43d70_0
  - lz4-c=1.9.2=he1b5a44_3
  - markupsafe=1.1.1=py38h1e0a361_1
  - matplotlib=3.3.1=1
  - matplotlib-base=3.3.1=py38h91b0d89_1
  - mercantile=1.1.6=pyh9f0ad1d_0
  - munch=2.5.0=py_0
  - ncurses=6.2=he1b5a44_1
  - netcdf4=1.5.4=nompi_py38hec8b9af_102
  - networkx=2.5=py_0
  - numpy=1.19.1=py38hbc27379_2
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1g=h516909a_1
  - orjson=3.3.1=py38h1e0a361_0
  - owslib=0.20.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.1=py38h950e882_0
  - parso=0.5.2=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.2.0=py38h9776b28_1
  - pip=20.2.2=py_0
  - pixman=0.38.0=h516909a_1003
  - pooch=1.1.1=py_0
  - poppler=0.87.0=h4190859_1
  - poppler-data=0.4.9=1
  - postgresql=12.3=h8573dbc_0
  - proj=7.0.0=h966b41f_5
  - prompt-toolkit=3.0.7=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py38_0
  - py3dep=0.1.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydaymet=0.1.3=py_0
  - pyepsg=0.4.0=py_0
  - pygeoogc=0.1.10=py_0
  - pygeoutils=0.1.10=py_0
  - pygments=2.6.1=py_0
  - pynhd=0.1.3=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py38h7521cb9_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.5=h1103e12_7_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py38h1e0a361_0
  - pyzmq=19.0.1=py38he6710b0_1
  - rasterio=1.1.5=py38h033e0f6_1
  - readline=8.0=he28a2e2_2
  - regionmask=0.6.1=py_0
  - requests=2.24.0=pyh9f0ad1d_0
  - rioxarray=0.0.31=py_0
  - rtree=0.9.4=py38h08f867b_1
  - scipy=1.5.2=py38h8c5af15_0
  - setuptools=49.6.0=py38h32f6830_0
  - shapely=1.7.1=py38hc7361b7_0
  - six=1.15.0=pyh9f0ad1d_0
  - snuggs=1.4.7=py_0
  - sqlite=3.33.0=h4cf870e_0
  - tbb=2020.2=hc9558a2_0
  - tiledb=1.7.7=h8efa9f0_3
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py38h1e0a361_1
  - traitlets=4.3.3=py38_0
  - tzcode=2020a=h516909a_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=py_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - xarray=0.16.0=py_0
  - xerces-c=3.2.2=h8412b87_1004
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.2=he6710b0_2
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2

